import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar'; // Import the Navbar
import Footer from './components/Footer'; // Import the Footer

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'talk2docs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-100`}>
        <Navbar /> {/* Add the Navbar here */}
        <main className="pt-20 p-10">
          {children} {/* Page content will be rendered here */}
        </main>
        <Footer />
      </body>
    </html>
  );
}